import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "로켓 AI_프론트엔드_포지션_지원자_이휘경 ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        {children}
      </body>
    </html>
  );
}
